### PR TITLE
Add a baseline app with a raw http handler to compare with kestrel

### PR DESCRIPTION
**Pull request by shhsu**

### CODE REVIEW

**Comment by shhsu** [comment]
@sivagms @SajayAntony

**Comment by shhsu** [comment]
rebased
ping @SajayAntony @sivagms

**Comment by SajayAntony** [comment]
+ @muratg since we need approval at this point

**Comment by muratg** [comment]
@SajayAntony Please send an email to @Eilon and @DamianEdwards for ask-mode approval.

**Comment by SajayAntony** [comment]
Move this under /test/Basline.BasicPlainText or something like that. The testapp is for dotnetcore apps .. Baselines should ideally live with the test folder.

**Pull request closed without merging**
