### PR TITLE
Remove the process architecture from search paths used to find dotnet

### PR DESCRIPTION
**Pull request by natemcmaster**
React to aspnet/BuildTools#341

Remove the process architecture from search paths used to find dotnet

### CODE REVIEW

**Comment by dougbu** [comment]
Not sure I understand completely removing "x64"  from all paths. The directory sometimes exists and, when it exists, that's where `dotnet.exe` is found.

**Comment by natemcmaster** [comment]
On Windows, we install to ~/.dotnet/x64 but linux and mac os its just ~/.dotnet. We did this because we were anticipating a dotnet feature that got cut. To simplify build tools and scripts, I want to remove<arch> from the default dotnet path on Windows.

**Comment by dougbu** [comment]
Discussed offline and decided to leave things as-is. We want the fallback (from `Process.GetCurrentProcess().MainModule.FileName`) to work on Windows. Windows users have `dotnet.exe` in to `$env:UserProfile\.dotnet\x64\` at least for now.

**Comment by natemcmaster** [comment]
Agreed.

**Pull request closed without merging**
