### PR TITLE
Remove unused projects

### PR DESCRIPTION
**Pull request by dougbu**
- Microsoft.AspNetCore.Tests.Throughput and SiteDensity used scripts that still mention `dnu`
- .NET 4.5 baseline projects can be found in old commits if needed
- Coldstart was yet-another test automation; I updated it a bit ago but haven't looked since

nits
- don't need samples folder with MSBuild infrastructure

### CODE REVIEW

**Comment by dougbu** [comment]
@rynowak you wanted a few removals from this repo. Anything I shouldn't have taken out?

**Comment by rynowak** [comment]
@dougbu - I'll be in the office tomorrow. Ok to sit together and go through these tomorrow AM?

**Comment by dougbu** [comment]
@rynowak sure.

In the meantime and FYI, almost every file in this PR has been deleted. Main question is whether anything is worth keeping around. So, might be enough for us to scan the list of files tomorrow.

Non-deletions (confirmed using `git diff dev --diff-filter=d --name-status`):
- [Performance.sln](https://github.com/aspnet/Performance/pull/214/files#diff-196aacd89c49571ab7e44c1db9937ac8)
- [src/Benchmarks.Utility/Helpers/PathHelper.cs](https://github.com/aspnet/Performance/pull/214/files#diff-2d7121ee366d9fea7b0b7834c0d15243)
- [testapp/MultipartPOST/README.md](https://github.com/aspnet/Performance/pull/214/files#diff-e3f50feed01852b39fe6dbfec9eddbd9)

**Comment by dougbu** [comment]
@mikeharder I discussed this PR w/ @rynowak and he had no issues with these removals. I'm going to send out a second PR to delete a few of the test apps as a result of that conversation.

We think you have more context on what I'm removing in this PR. Please comment if you think anything should be preserved (beyond the `git` history).

**Comment by dougbu** [comment]
7b59887

**Pull request closed without merging**
