### PR TITLE
Add multipart form POST scenario into the stress/reliability test mix

### PR DESCRIPTION
**Pull request by yuwaMSFT**
@sivagms @SajayAntony

### CODE REVIEW

**Comment by SajayAntony** [comment]
Is this after discussion with folks regarding an acceptable scenario?

**Comment by yuwaMSFT** [comment]
Yes...According to Chris a multipart form with a 1 – 50mb file body should be supported, although for stress/reliability test we can go further. 

For now, just add a simple scenario in the mix with the following data:
1. 5 parts/sections in the content
2. each part/section has about 4MB data.

**Comment by SajayAntony** [comment]
:shipit:

**Comment by SajayAntony** [comment]
@DavidObando

**Comment by yuwaMSFT** [comment]
Manually merged to dev

**Pull request closed without merging**
