### PR TITLE
Reliablity issue #144 Add a stress test to register to ClientDisconnectionToken

### PR DESCRIPTION
**Pull request by yuwaMSFT**
Reliablity issue #144 Add a stress test to register to ClientDisconnectionToken

Description: Add a test controller in the test app to do "chained" requests with timeout support
If user specifies a short timeout, somewhere in the chained requests would time out and cancel, triggering the cancellation of other outstanding async requests as well.

Also add the scenario into the stress/reliability test mix.

### CODE REVIEW

**Comment by yuwaMSFT** [comment]
@SajayAntony @sivagms @KKhurin

**Comment by KKhurin** [comment]
Is it possible to add timeoutMs=0 (or some very small timespan)? This should help exercising the code paths where the cancellations happen early in begin / connect stages.

**Comment by yuwaMSFT** [comment]
@KKhurin Added request with timeoutMs=0 in the mix.

**Comment by yuwaMSFT** [comment]
Manually merged to dev.

**Pull request closed without merging**
