### PR TITLE
* Unbreak the build *

### PR DESCRIPTION
**Pull request by rynowak**
- Fix references (fallout from changes in other repos)
- React to Hosting change
- React to EF change

There are still failing tests here, but this should unblock the build.

### CODE REVIEW

**Comment by muratg** [comment]
Thanks @rynowak!

cc @SajayAntony

**Comment by SajayAntony** [comment]
:+1: thanks @rynowak

**Comment by SajayAntony** [comment]
:joy_cat: `unbreak-my-heart`

**Comment by muratg** [comment]
:joy:

**Pull request closed without merging**
