### PR TITLE
React to changes in MVC

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by javiercn** [comment]
@DavidObando

**Comment by DavidObando** [comment]
:shipit:

**Comment by SajayAntony** [comment]
@javiercn do you want to merge this?

**Comment by javiercn** [comment]
I think @DavidObando already did, or did the same change himself. I think this can be closed

**Comment by DavidObando** [comment]
I added it to #108 but haven't committed it. I'll be updating this soon, sorry for the inconvenience. I'll close Javier's PR.

**Pull request closed without merging**
