### PR TITLE
Add option to run either stress test or reliability test.

### PR DESCRIPTION
**Pull request by yuwaMSFT**
For stress test, we put load to maximum.
For reliability test, currently we are targetting an average CPU usage of <80% on an A2 VM in Azure

Run the script:
	wcatrun.bat servername serverport [reliability/stress]

	If the 3rd parameter is not specified, it runs reliability test.

### CODE REVIEW

**Comment by yuwaMSFT** [comment]
@sivagms @SajayAntony

**Comment by SajayAntony** [comment]
Please update the ReadMe as well.

**Comment by SajayAntony** [comment]
:shipit:  Please merge manually into dev without --no-ff

**Comment by SajayAntony** [comment]
Also please squash with rebase -i

**Comment by yuwaMSFT** [comment]
Merged manually into dev.

**Pull request closed without merging**
