### PR TITLE
Remove unnecessary test sites

### PR DESCRIPTION
**Pull request by dougbu**
- BasicKestrelJson, HelloWorldMvc, HelloWorldMvcCore, LargePageMvc, PlainTextMvc, StressMvc
- most duplicate other projects or those in aspnet/Benchmarks

Should KestrelLargeStaticFile, KestrelShutdown, LargeJsonApi, MultipartPOST, and PooledKestrel also go?
- only PooledKestrel seems at all useful; @benaadams created that one
  - should that configuration be in Benchmarks?

### CODE REVIEW

**Comment by benaadams** [comment]
Drop PooledKestrel; has drifted too much

**Comment by dougbu** [comment]
:up::date: to rebase on `dev` and remove Pooled Kestrel site

**Comment by rynowak** [comment]
`LargeJsonApi` needs to stay

**Comment by dougbu** [comment]
e165014

**Pull request closed without merging**
