### PR TITLE
Enable server GC for all 'app' projects

### PR DESCRIPTION
**Pull request by rynowak**
/cc @SajayAntony @DavidObando - can you think of a reason **not** to enable server GC for any of these projects?

### CODE REVIEW

**Comment by DavidObando** [comment]
Looks good to me. :shipit: 

@sivagms any objections?

**Comment by SajayAntony** [comment]
:shipit: Makes sense. 
We need to run the test with workstation GC explicitly in some cases. But that can be modified during the run.

**Comment by sivagms** [comment]
yes, we'll modify it if needed for the workstation gc

**Comment by sivagms** [comment]
but the default should be servergc

**Pull request merged**
