### PR TITLE
Fixes infinite loop in BasicKestrel test

### PR DESCRIPTION
**Pull request by DavidObando**
The code tried to write a file and increased a counter when it failed. Retries a max of 3 times, but the successful case wasn't breaking the loop in any way and the test gets stuck re-writing the file forever. This fixes the situation.

/cc @troydai @NTaylorMullen @SajayAntony

### CODE REVIEW

**Comment by DavidObando** [comment]
Forgot to mention that this fixes #40.

**Comment by troydai** [comment]
Yup. :shipit:

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by SajayAntony** [comment]
Sweet

**Pull request merged**
